[package]
name = "openexr-rs"
version = "0.1.0"
authors = ["a <a@a.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
openexr-sys = { path = "../openexr-sys" }
semver = "0.11.0"
mint = "0.5.6"
anyhow = "1.0.38"